export default {
  GET_USER: 'GET_USER',
  SET_USER: 'SET_USER',

  JOINED_RANDOM: 'JOINED_RANDOM',
  RECEIVED_RANDOM: 'RECEIVED_RANDOM',
  LEAVED_RANDOM: 'LEAVED_RANDOM',
  CLEAN_RANDOM: 'CLEAN_RANDOM',

  GET_CHANNEL: 'GET_CHANNEL',
  ADD_CHANNEL: 'ADD_CHANNEL',
  ADDED_CHANNEL: 'ADDED_CHANNEL'
};