const msgTypes = {
  JOIN_RANDOM: 'JOIN_RANDOM',
  JOINED_RANDOM: 'JOINED_RANDOM',

  SEND_RANDOM: 'SEND_RANDOM',
  RECEIVE_RANDOM: 'RECEIVE_RANDOM',

  JOIN_OPEN: 'JOIN_OPEN',
  JOINED_OPEN: 'JOINED_OPEN',

  SEND_OPEN: 'SEND_OPEN',
  RECEIVE_OPEN: 'RECEIVE_OPEN'
};

export default msgTypes;