const msgTypes = {
  JOIN_RANDOM: 'JOIN_RANDOM',
  JOINED_RANDOM: 'JOINED_RANDOM',

  SEND_RANDOM: 'SEND_RANDOM',
  RECEIVE_RANDOM: 'RECEIVE_RANDOM',

  LEAVE_RANDOM: 'LEAVE_RANDOM',
  LEAVED_RANDOM: 'LEAVED_RANDOM',

  JOIN_OPEN: 'JOIN_OPEN',
  JOINED_OPEN: 'JOINED_OPEN',

  SEND_OPEN: 'SEND_OPEN',
  RECEIVE_OPEN: 'RECEIVE_OPEN',

  LEAVE_OPEN: 'LEAVE_OPEN',
  LEAVED_OPEN: 'LEAVED_OPEN'
};

export default msgTypes;